// Package frontmatter parses a leading YAML metadata block:
//
//	---
//	title: Hello
//	---
//
// It is a trimmed port of the parser half of github.com/yuin/goldmark-meta
// v1.1.0 to goldmark v2. See LICENSE in this directory for the original MIT
// terms and copyright (c) 2019 Yusuke Inuzuka.
//
// Changes from upstream:
//   - Ported to the goldmark/v2 API. ast.TextBlock, which upstream used to
//     hold the raw block, no longer exists, so this package carries its own
//     block node that renders its children with no wrapper.
//   - Only the ordered form of the metadata is decoded. Upstream unmarshals
//     twice, once into a map and once into a MapSlice; markbrowse renders the
//     table itself and needs document order, so the map is dead weight.
//   - The table renderer and the document-storage option are gone: markbrowse
//     builds its own GitHub-style metadata table from Items.
//   - The YAML error comment has "-->" stripped from it. Upstream interpolates
//     the error straight into an HTML comment, and an error message is partly
//     derived from document content.
package frontmatter

import (
	"bytes"
	"fmt"
	"io"
	"strings"

	"github.com/yuin/goldmark/v2/ast"
	"github.com/yuin/goldmark/v2/parser"
	"github.com/yuin/goldmark/v2/renderer"
	"github.com/yuin/goldmark/v2/renderer/html"
	"github.com/yuin/goldmark/v2/text"
	"github.com/yuin/goldmark/v2/util"
	"gopkg.in/yaml.v2"
)

// contextKey holds the parsed metadata for one parse invocation.
var contextKey = parser.NewContextKey()

type data struct {
	Items yaml.MapSlice
	Error error
	Node  *Block
}

// Items returns the front matter of the document just parsed, in the order the
// keys appear in the source. It returns nil when there is no front matter or
// when the YAML failed to parse.
func Items(pc parser.Context) yaml.MapSlice {
	v, _ := pc.Get(contextKey).(*data)
	if v == nil {
		return nil
	}
	return v.Items
}

// KindBlock is the node kind of a front matter block that failed to parse.
var KindBlock = ast.NewNodeKind("FrontMatterBlock")

// Block holds the raw front matter. A block that parses is removed from the
// document; one that does not stays put and renders as plain text, so a broken
// metadata block is visible to whoever wrote it.
type Block struct {
	ast.BaseBlock
}

// Kind implements ast.Node.
func (n *Block) Kind() ast.NodeKind { return KindBlock }

// Dump implements ast.Node.
func (n *Block) Dump(_ []byte) *ast.NodeDump { return ast.NewNodeDump(n, nil) }

// NewBlock builds a front matter block.
func NewBlock() *Block {
	n := &Block{}
	n.Init(n)
	return n
}

// KindError is the node kind of the YAML parse error comment.
var KindError = ast.NewNodeKind("FrontMatterError")

// Error is an HTML comment carrying the YAML parse error, appended after a
// front matter block that failed. It is its own node rather than an
// ast.RawHTML because raw HTML is suppressed unless the renderer is in unsafe
// mode, and this diagnostic is generated by us, not by the document.
type Error struct {
	ast.BaseInline

	Message string
}

// Kind implements ast.Node.
func (n *Error) Kind() ast.NodeKind { return KindError }

// Dump implements ast.Node.
func (n *Error) Dump(_ []byte) *ast.NodeDump {
	return ast.NewNodeDump(n, map[string]any{"Message": n.Message})
}

// NewError builds the error comment node.
func NewError(msg string) *Error {
	n := &Error{Message: msg}
	n.Init(n)
	return n
}

// isSeparator reports whether a line is the "---" fence.
func isSeparator(line []byte) bool {
	line = util.TrimRightSpace(util.TrimLeftSpace(line))
	if len(line) == 0 {
		return false
	}
	for _, c := range line {
		if c != '-' {
			return false
		}
	}
	return true
}

type blockParser struct{}

var _ parser.BlockParser = (*blockParser)(nil)

func (b *blockParser) Trigger() []byte { return []byte{'-'} }

func (b *blockParser) Open(_ ast.Node, reader text.Reader, _ parser.Context) (ast.Node, parser.State) {
	// Front matter is only front matter on the first line of the document.
	if linenum, _ := reader.Position(); linenum != 0 {
		return nil, parser.NoChildren
	}
	if line, _ := reader.PeekLine(); isSeparator(line) {
		return NewBlock(), parser.NoChildren
	}
	return nil, parser.NoChildren
}

func (b *blockParser) Continue(node ast.Node, reader text.Reader, _ parser.Context) parser.State {
	line, segment := reader.PeekLine()
	if isSeparator(line) && !util.IsBlank(line) {
		reader.Advance(segment.Len())
		return parser.Close
	}
	// The block's source is both the YAML to decode and, if decoding fails,
	// the text to show. AppendSource lives on ast.BlockNode in v2, not on
	// ast.Node.
	if block, ok := node.(ast.BlockNode); ok {
		block.AppendSource(segment)
	}
	return parser.Continue | parser.NoChildren
}

func (b *blockParser) Close(node ast.Node, reader text.Reader, pc parser.Context) {
	block, ok := node.(*Block)
	if !ok {
		return
	}

	var buf bytes.Buffer
	for _, segment := range block.Source() {
		buf.Write(segment.Bytes(reader.Source()))
	}

	d := &data{Node: block}
	// Only the ordered form is decoded: markbrowse renders the table itself
	// and needs the document's key order.
	var items yaml.MapSlice
	if err := yaml.Unmarshal(buf.Bytes(), &items); err != nil {
		d.Error = err
	} else {
		d.Items = items
	}
	pc.Set(contextKey, d)

	if d.Error == nil {
		if parent := block.Parent(); parent != nil {
			parent.RemoveChild(block)
		}
	}
}

func (b *blockParser) CanInterruptParagraph() bool { return false }

func (b *blockParser) CanAcceptIndentedLine() bool { return false }

// errorTransformer appends the parse error after a block that failed, once the
// document is otherwise complete.
type errorTransformer struct{}

var _ parser.ASTTransformer = (*errorTransformer)(nil)

func (t *errorTransformer) Transform(_ *ast.Document, _ text.Reader, pc parser.Context) {
	d, _ := pc.Get(contextKey).(*data)
	if d == nil || d.Error == nil || d.Node == nil {
		return
	}
	d.Node.AppendChild(NewError(d.Error.Error()))
}

// blockRenderer renders the raw block with no wrapping element, matching the
// ast.TextBlock this node replaced: children only, plus the trailing newline
// goldmark v1 wrote when a non-empty text block was followed by a sibling.
type blockRenderer struct{}

func (r *blockRenderer) Render(w io.Writer, _ []byte, n ast.Node, entering bool, _ renderer.Context) (ast.WalkStatus, error) {
	if entering || n.NextSibling() == nil || n.FirstChild() == nil {
		return ast.WalkContinue, nil
	}
	bw, ok := w.(util.BufWriter)
	if !ok {
		return ast.WalkStop, fmt.Errorf("frontmatter: renderer needs a util.BufWriter, got %T", w)
	}
	_ = bw.WriteByte('\n')
	return ast.WalkContinue, nil
}

// errorRenderer writes the YAML error as an HTML comment.
type errorRenderer struct{}

func (r *errorRenderer) Render(w io.Writer, _ []byte, node ast.Node, entering bool, _ renderer.Context) (ast.WalkStatus, error) {
	n, ok := node.(*Error)
	if !ok || !entering {
		return ast.WalkContinue, nil
	}
	bw, ok := w.(util.BufWriter)
	if !ok {
		return ast.WalkStop, fmt.Errorf("frontmatter: renderer needs a util.BufWriter, got %T", w)
	}

	// A YAML error message quotes the input that produced it, so it must not
	// be able to close the comment it is being written into.
	msg := strings.ReplaceAll(n.Message, "-->", "--&gt;")
	_, _ = bw.WriteString("<!-- ")
	_, _ = bw.WriteString(msg)
	_, _ = bw.WriteString(" -->")
	return ast.WalkContinue, nil
}

type parserExtension struct{}

// NewParser returns the front matter parser extension.
func NewParser() parser.Extension { return &parserExtension{} }

func (e *parserExtension) ParserOptions(_ *parser.Config) []parser.Option {
	return []parser.Option{
		parser.WithBlockParsers(util.Prioritized[parser.BlockParser](&blockParser{}, 0)),
		parser.WithASTTransformers(util.Prioritized[parser.ASTTransformer](&errorTransformer{}, 0)),
	}
}

type htmlRendererExtension struct{}

// NewHTMLRenderer returns the front matter renderer extension.
func NewHTMLRenderer() html.Extension { return &htmlRendererExtension{} }

func (e *htmlRendererExtension) RendererOptions(_ *html.Config) []html.Option {
	return []html.Option{
		html.WithNodeRenderers(map[ast.NodeKind]html.NodeRenderer{
			KindBlock: &blockRenderer{},
			KindError: &errorRenderer{},
		}),
	}
}
